include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"ili9881_dsi_vdo_hd720_txd_aw1055")
obj-y   +=  ili9881_dsi_vdo_hd720_txd_aw1055.o
endif
